import { AppSidebar } from "@/components/app-sidebar"
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function AppLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <SidebarProvider>
      <AppSidebar/>
      <div className="px-8">
          <SidebarTrigger/>
          {children}
      </div>
    </SidebarProvider>
  )
}
